### ISSUE TITLE
:sparkles: Consider changing license

### ISSUE THREAD

**Issue by nul800sebastiaan** [eduwardpost/uActivityPub#73]
**Is your feature request related to a problem? Please describe.**
This looks like a great project but for many people the GPL license is too restrictive/risky. You might have very good reason to choose this license though, so feel free to close this is you did!

**Describe the solution you'd like**
The MIT license is a great fit for most Umbraco plugins, others use the Mozilla Public License, can either of those be considered?

Thanks for your considerating!

**Comment by eduwardpost** [comment]
Thank you for the interest and taking the time to reply.
This is my first (proper) open source project. 

In my (short) research into the different open source licenses the only (major) difference between the MIT and GPL licenses I found was that the GPL license says that if you use the open source code to distribute a derivative product from this source that you also have to make it open source (under GPL). 

So i'm not entirely sure how that would be to restrictive, unless I misunderstood it and that the GPL license means that you cannot use this in a closed source project (with or without modifications to the code).

I am of course happy to learn more about this. As I have not chosen any specific reason for the GPL license other then that it would mean the project (and any possible derivatives) are remain open source. and would definitely consider changing the license if I missed or misunderstood something.

**Comment by leekelleher** [comment]
@eduwardpost It's great to see an ActivityPub package for Umbraco, it's great to see the fediverse expanding! 😀 

With regards to the licensing, the issue with using GPL for a package in the Umbraco ecosystem is that the majority of implementors are commercial agencies, which would mean that if they used it, they'd be obliged to open-source their implementation code, also under GPL 3.0.  Which they wont want to do because they are typically closed-source.

I mean, who actually polices this? But any company with due diligence probably would steer clear of it. 🤷 

If you want to stick with a GPL style license, then L-GPL 3.0 might be a better fit.

Having developed Umbraco packages for several years, I've found that either the MIT or Mozilla licenses to be a better fit within the Umbraco ecosystem.  Personally, I go with Mozilla Public License 2.0 these days, as it states that any modifications would need to be made public as open-source.

Open source licensing can be a minefield, in some ways it doesn't matter, but if you would like a wider adoption (of your package), then a less restrictive license can be preferable.  GitHub has a lot of useful information at: https://choosealicense.com

I hope this helps and doesn't come across as interfering, just wanted to share my insights from doing Umbraco package development for many years. ❤️

**Comment by eduwardpost** [comment]
First off let me start by saying that it is not at all interfering, if anything this is what opensource is about collaborating together. Secondly I'm happy to hear there's already about 2 people more interested in this then i would've expected ;) 

I did not understand correctly that using the GPL license means that you are not able to use the package in a closed source project. The only goal I had in mind (besides protection) is that if someone takes the source code and redistributes it that it also would have to be as open source.

I'll be changing the license to the Mozilla Public License 2.0.
